input{
        stdin{}
}

filter{
        grok {
                match => { "message" => "%{TIMESTAMP_ISO8601:logDatetime} \[(?<logThread>[^\[\]]+)\] %{WORD:logLevel} \[(?<logClass>[^\[\]]+)\] - (?<logMessage>(.*)+)" }
        }
}

output{
        stdout{
                 codec => rubydebug
        }
        
        elasticsearch{
                hosts => "106.15.42.147:9200"
                index => "testlog-%{+YYYY.MM.dd}"
        }
}
